- hosts: hbase 
  remote_user: root
  vars_files:
   - vars/user.yml
   - vars/var_basic.yml
   - vars/var_master.yml
   - vars/var_hbase.yml
  vars:
     open_firewall: true
     install_hbase: false
     config_hbase: true
  roles:
    - hbase
